### ISSUE TITLE
Package for Node v20.11.0

### ISSUE THREAD

**Issue by ADobin** [AArnott/Node.js.redist#12]
The latest LTS for Node is `20.11.0`. Normally I wouldn't file an issue since `20.9.0` is available but importantly for my use case (and anyone else using `jest`) Node `20.10.0` contained a [performance fix](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#vm-fix-v8-compilation-cache-support-for-vmscript). Would it be possible to get the latest LTS published with this performance fix?

**Comment by AArnott** [comment]
[Done](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=9019&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=53352b99-bc56-513f-dcdf-57009ff4318b), although the symbols package has exceeded the maximum size so it failed.
