### ISSUE TITLE
Support for updates of older versions (eg. LTS releases)

### ISSUE THREAD

**Issue by flcdrg** [AArnott/Node.js.redist#2]
Would it be possible to extend the scripts so they push newer versions for older releases.. eg. the latest 12 LTS is 12.14.1

Is the pipelines build scheduled to run daily (so that this would probably just be a change to the scripts), or do you only run it on demand?

**Comment by AArnott** [comment]
There's no schedule. I do it on-demand. 
I just pushed 12.14.1 to nuget.org for you.
