### ISSUE TITLE
Node.js.redist doesn't contain npm

### ISSUE THREAD

**Issue by nayanshah** [AArnott/Node.js.redist#3]
The script downloads the Windows Binaries zip (e.g. [v12.14.1](https://nodejs.org/dist/v12.14.1/node-v12.14.1-win-x64.zip) ) which contains npm as well. But then only extracts and packs node.exe

Is there a specific reason to not include npm? Is there an alternate NuGet package for acquiring npm?

**Comment by AArnott** [comment]
Good question. This package is only meant to redist the runtime. If you're using npm, you're under development and I wonder why you don't just install node the ordinary way.

**Comment by nayanshah** [comment]
I'm looking at options for bootstrapping node+npm on build machines. Fetching tool packages from AzureDevOps feeds is preferred over downloading directly from external websites.

**Comment by AArnott** [comment]
Azure Pipelines has a node tool installer task. Are you concerned about using that?

**Comment by nayanshah** [comment]
This is for CloudBuild machines which don't run Azure Pipelines tasks. Things which aren't part of the default machine SKU are fetched using AzureDevOps feeds or Artifact Services.

**Comment by AArnott** [comment]
OK. Well, if it doesn't substantially increase the size of the package, I guess we can modify the existing one. Otherwise maybe we should create more packages. We already have a symbols and no symbols pair of packages that we publish. We could add an npm-included package as well.

**Comment by AArnott** [comment]
Another question: why not just download the node.js zip file on the build agent if you want everything in it? Is there some reason nuget is that much better of a distribution mechanism?

**Comment by kskalski** [comment]
Personally I used it as versioning and download mechanism as well as for having a canonical path to access those tools. Nowadays I switched to rely on Visual Studio's installation and my build has magic like this:
```
NODE_EXE=$(shell echo '$(MSBUILD)' | sed 's/\*\/Bin.*/Microsoft\/VisualStudio\/NodeJs\/node.exe/')
NPM_CLI=$(shell wslpath -w $(patsubst %node.exe,%node_modules/npm/bin/npm-cli.js,$(NODE_EXE)))
```

**Comment by AArnott** [comment]
I looked more into this and including npm would require putting several thousand more files into the package. That's a significant scope change, so I'm gonna say it's not within the purposes of this repo.
