### ISSUE TITLE
How do I copy the files contained in the package to the output folder of a .NET project/solution?

### ISSUE THREAD

**Issue by lstefano71** [AArnott/Node.js.redist#5]
At the risk of making a fool of myself...
I have have added the package to the list of dependencies of a .NET project (in Visual Studio, but I guess it does not really matter).
```
  <ItemGroup>
    <PackageReference Include="Node.js.redist" Version="14.2.0" />
  </ItemGroup>
```

Restore has downloaded the package. But its content remains in the machine-wide cache for nuget packages. (`blabla\.nuget\packages\node.js.redist\14.2.0\tools\win-x64\node.exe`)
How do I copy those files in the output folder of the project (`blabla\bin\debug\net5.0\` for instance)?
Thank you in advance.

**Comment by AArnott** [comment]
First, add the `GeneratePathProperty` attribute to your reference:

```xml
<PackageReference Include="Node.js.redist" Version="14.2.0" GeneratePathProperty="true" />
```

Then in your project file add:

```xml
<None Include="$(PkgNode_js_redist)\tools\win-x86\node.exe">
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
```

I haven't tested this, so it might be a bit off. But that's the general idea.

**Comment by lstefano71** [comment]
For the record and future reference: not off at all. In fact, spot on. Thank you again. Much appreciated!

**Comment by kmiterror** [comment]
Wouldnt it be better if you would place those files in `runtimes/[runtime_identifier]/native` folder?
Where `[runtime_identifier]` is one of `win-x64/win-x86/osx-x64/osx-arm64/linux-x64`

Then we could just use something like 
```
<PackageReference Include="adk-build-tools" Version="31.0.0">
    <IncludeAssets>runtime; native</IncludeAssets>
</PackageReference>
```
doing it that way will automatically resolve proper version basing on what RuntimeIdentifier was set at build time.

**Comment by AArnott** [comment]
@kmiterror  That assumes consumption of this package by .NET projects, and that those .NET applications want to invoke node.js at runtime. But as this package contains a runtime of its own, it is quite often consumed by non-.NET projects where nuget.org is only serving as a convenient way to download node.js.
That's not to say this is a bad idea, or incompatible with other use cases. But given we already have many versions published with a particular file layout, it would likely be disruptive to existing users if that layout were to change, so I'm inclined to leave it alone at this point.
